### ISSUE TITLE
Font-specific metadata locations for linux don't follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by janc13** [steinbergmedia/smufl#1]
Font-specific metadata locations for linux (as defined in [`font-metadata-locations.md`](https://github.com/steinbergmedia/smufl/blob/master/font-metadata-locations.md)) should follow the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/latest/).

Specifically, system-wide font metadata files should be searched in `$XDG_DATA_DIRS/SMuFL/Fonts/<fontname>/<fontname>.json` (which can be multiple locations), while local metadata should be in `$XDG_DATA_HOME/SMuFL/Fonts/<fontname>/<fontname>.json`.

See the XDG Base Directory Specification for more info.

(Also, I haven't read the whole SMuFL specification, so their might be other places than `font-metadata-locations.md` where this applies.)

**Comment by dspreadbury** [comment]
Now that SMuFL is being developed as part of the W3C Music Notation Community Group, please direct issues to that repository. I've recreated this issue in that repository here:

https://github.com/w3c/smufl/issues/39
